	<p><strong>Erreur lors de l'activation!</strong></p>
		
	<p>La clé d'activation fournie est manquante ou ne peut plus être utilisée
		 pour une activation de compte. Veuillez réintroduire une demande d'activation
		 de compte à l'aide de <a onclick="javascript:show_form('/accounts/lost-password', 300)">ce formulaire</a></p>

	<p>Si le problème persiste, veuillez prendre contact avec le webmaster à l'adresse
		 <a href="mailto:team-web.uclouvain@acm-sc.be">team-web.uclouvain@acm-sc.be</a>.</p>
