<div class="message ok-message">
	<h3>Votre compte a été activé!</h3>
		
	<p>Vous êtes maintenant authentifié sur notre site et avez accès à certaines
		 fonctionnalités supplémentaires:</p>
	
	<ul>
		<li>Pour modifier les informations vous concernant ou vos paramètres cliquez
				<a onclick="javascript:show_form('/accounts/update', 460)">ici</a></li>
	</ul>

	<a onclick="hide_popup()">Fermer</a>
</div>