#!/bin/sh
#

git branch -l | grep " test " > /dev/null 2>&1
if [ $? -eq 0 ]; then
	git branch -D test > /dev/null
	if [ $? -ne 0 ] ; then
		echo "Unable to remove the test branch"
		exit 1
	fi
fi

echo "Update remote branch (can take a while)"
git remote update > /dev/null 2>&1

current_branch=`git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`

git branch -f test webmaster/test > /dev/null 2>&1
if [  $? -ne 0 ]; then
	echo "Unable to create a new branch based on webmaster/test"
	exit 1
fi

echo -n "Rebasing "
echo -n ${current_branch}
echo " on test"

git rebase test > /dev/null 2>&1
if [  $? -ne 0 ]; then
	echo "Unable to rebase the branch on test (try it interactively)"
	exit 1
fi

git checkout test > /dev/null 2>&1
if [  $? -ne 0 ]; then
	echo "Unable to checkout test"
	exit 1
fi

echo -n "Merging "
echo -n ${current_branch}
echo " on test"

git merge ${current_branch} > /dev/null 2>&1
if [  $? -ne 0 ]; then
	echo "Unable to merge the current branch"
	exit 1
fi

echo "Pushing changes on webmaster/test"

git push webmaster test > /dev/null 2>&1
if [  $? -ne 0 ]; then
	echo "Unable to push on webmaster (do you have sufficient rights?)"
	exit 1
fi

git checkout master > /dev/null 2>&1
if [  $? -ne 0 ]; then
	echo "Unable to checkout master"
	exit 1
fi

git branch -D test > /dev/null 2>&1
if [  $? -ne 0 ]; then
	echo "Unable to delete test"
	exit 1
fi

echo "Updating test version on server"

ssh acmscw@chapter.info.ucl.ac.be /home/acmscw/update-test > /dev/null 2>&1
if [  $? -ne 0 ]; then
	echo "Unable to update version on the server"
	exit 1
fi
